### Get authenticated user
GET http://localhost/api/user
Accept: application/json
Authorization: Bearer 10|pSr1Q9XNkaEIUbwpTzN0AIdC5m2MlAIAtOWEsJZs99b692d3

### Login
POST http://localhost/api/login
Accept: application/json
content-type: application/json

{
    "email": "test@example.com",
    "password": "password"
}

### Test route
GET http://localhost/api/test
Accept: application/json

### Get topics
GET http://localhost/api/topics
Accept: application/json

### Get posts
GET http://localhost/api/posts
Accept: application/json

### Get post
GET http://localhost/api/posts/10
Accept: application/json

### Create post
POST http://localhost/api/posts
accept: application/json
content-type: application/json
Authorization: Bearer 10|pSr1Q9XNkaEIUbwpTzN0AIdC5m2MlAIAtOWEsJZs99b692d3

{
    "title": "My first post",
    "slug": "my-first-post-wef",
    "description": "This is a test post description",
    "topic_id": 8,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}


### Update post
PUT http://localhost/api/posts/1
accept: application/json
content-type: application/json

{
    "title": "Test post updated",
    "slug": "test-post-2",
    "description": "This is a test post description updated",
    "topic_id": 1,
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}


### Delete post
DELETE http://localhost/api/posts/1
accept: application/json
content-type: application/json
