@url = {{ $dotenv APP_URL }}/api

### Login
# @name login
# @prompt email
# @prompt password
POST {{url}}/login
Accept: application/json
content-type: application/json

{
    "email": "{{ email }}",
    "password": "{{ password }}"
}

###

@token = {{ login.response.body.token }}

### Get authenticated user
GET {{url}}/user
Accept: application/json
Authorization: Bearer {{ token }}

### Test route
GET {{url}}/test
Accept: application/json

### Get topics
GET {{url}}/topics
Accept: application/json

### Get posts
GET {{url}}/posts
Accept: application/json

### Get post
# @prompt post_id
GET {{url}}/posts/{{ post_id }}
Accept: application/json

### Create post
# @prompt title
# @prompt slug
# @prompt topic_id
# @prompt description
# @prompt content
POST {{url}}/posts
accept: application/json
content-type: application/json
Authorization: Bearer {{ token }}

{
    "title": "{{ title }}",
    "slug": "{{ slug }}",
    "topic_id": "{{ topic_id }}",
    "description": "{{ description }}",
    "content": "{{ content }}"
}


### Update post
# @prompt post_id
# @prompt title
# @prompt slug
# @prompt topic_id
# @prompt description
# @prompt content
PUT {{url}}/posts/{{ post_id }}
accept: application/json
content-type: application/json
Authorization: Bearer {{ token }}

{
    "title": "{{ title }}",
    "slug": "{{ slug }}",
    "topic_id": "{{ topic_id }}",
    "description": "{{ description }}",
    "content": "{{ content }}"
}

### Delete post
# @prompt post_id
DELETE {{url}}/posts/{{ post_id }}
accept: application/json
content-type: application/json
Authorization: Bearer {{ token }}


### Comment on post
# @prompt post_id
# @prompt comment
POST {{url}}/posts/{{ post_id }}/comments
accept: application/json
content-type: application/json
Authorization: Bearer {{ token }}

{
    "comment": "{{ comment }}"
}

### Comments on post
# @prompt post_id
GET {{url}}/posts/{{ post_id }}/comments
accept: application/json
content-type: application/json


### Reply to comment
# @prompt comment_id
# @prompt message
POST {{url}}/comments/{{ comment_id }}/replies
accept: application/json
content-type: application/json
Authorization: Bearer {{ token }}

{
    "message": "{{ message }}"
}
